name: softlearning-robustness
channels:
- defaults
- conda-forge
dependencies:
- python>=3.7,<3.8
- pip>=19.3
- conda>=4.7
- pyopengl-accelerate==3.1.3b1
# - cudatoolkit==10.1.243
# - cudnn
- pip:
    - -r ./requirements.txt
